version: '3.9'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: A!VeryComplex123Password
      MSSQL_DBNAME: RegistrationLettersDb
    ports:
      - "1433:1433"